### ISSUE TITLE
Tidal Power Performance Functions 

### ISSUE THREAD

**Issue by rpauly18** [MHKiT-Software/MHKiT-Python#165]
### Performance submodule
- [ ] Review upcoming DOLfYN functions for overlap with IEC guidance
- [ ] develop functions for completing power performance assessment from tidal turbine 
- [ ] higher level function for tidal device performance

**Comment by jmcvey3** [comment]
@ssolson @hivanov-nrel  Dumb question (asking yall since my vscode has you plus Kelly listed as contributors): In `mhkit/river/performance`, the "circular" and "ducted" functions contain this line: `projected_capture_area = 4.*np.pi*(equivalent_diameter**2)` . Shouldn't that be `projected_capture_area = (1/4)*np.pi*(equivalent_diameter**2)`?
