### ISSUE TITLE
Dolfyn reader estimates the number of pings in the file based on the length in bytes of the first ping

### ISSUE THREAD

**Issue by browniea** [MHKiT-Software/MHKiT-Python#206]
### Describe the bug:
Comparing data from a Teledyne river pro ADCP processed by Teledyne software WinRiver to processing it in dolfyn. The data had 9020 points in  WinRiver and only 6507 points in dolfyn. 

### Problem:
The found issue is that the Dolfyn reader estimates the number of pings in the file based on the length in bytes of the first ping. For this file the first data point is 1700 bytes and the others are 1200 bytes. 

*Referencing data collected on 7/1/2022 on the Tanana River near Nenana Alaska.

**Comment by jmcvey3** [comment]
I copied over a function from the nortek.py reader that estimates the length of the file based on the average of the first 50 pings, instead of the first. This solution allows dolfyn to read 8952 pings of the total 9020; the missing pings leave the last 56 s of the file unread. This may or may not be an issue depending on when the ADCP is turned off after data collection.

The number of pings in a file isn't saved in header information, so the only foolproof way to get the entire file length is to first manually read the entire file, which increases processing time.
