### ISSUE TITLE
Examples will not run

### ISSUE THREAD

**Issue by SeanPluemer** [MHKiT-Software/MHKiT-Python#24]
Any example where the code is calling for the data in the examples folder will not run as they stand. 
For example:  
``# Load data from the csv file into a DataFrame``
``data = pd.read_csv('data/wave_elevation_data.csv', index_col='Time') ``
will result this error message: 
``FileNotFoundError: [Errno 2] File data/wave_elevation_data.csv does not exist: 'data/wave_elevation_data.csv'``

The only way I was able to get the code to run was by changing it to this:
``# Load data from the csv file into a DataFrame``
``data = pd.read_csv(r'C:\users\pluem\documents\MHKiT-Python\examples\data/wave_elevation_data.csv', index_col='Time') ``

**Comment by kmruehl** [comment]
@SeanPluemer which example are you trying to run? 

All of these examples should run as using a relative path since the data is included in the examples directory on GitHub: https://github.com/MHKiT-Software/MHKiT-Python/tree/master/examples/data. You should not need to specify a direct path to get the example to run. This may mean that the relative path for this example is incorrect.

**Comment by kmruehl** [comment]
@SeanPluemer it looks like you're running https://github.com/MHKiT-Software/MHKiT-Python/blob/master/examples/qc_example.ipynb. This should run as a relative path if you are in the correct directory.

**Comment by rpauly18** [comment]
I just tried running the qc example that I believe @SeanPluemer was running. It ran just fine for me using the relative path. So, not sure what the issue is. Perhaps something has changed in the paths on your computer. I had also had my intern run these examples a while back and he said they ran fine as they were.

**Comment by kmruehl** [comment]
@rpauly18 I agree. The relative path should work as is.

**Comment by ssolson** [comment]
As it stands there is nowhere in the examples/ documentation which directs the user to run/ look for the data using a relative path correct? Essentially running the example from the examples folder.

**Comment by kmruehl** [comment]
@ssolson The header of this example states "The data file used in this example is stored in the \MHKiT\examples\data directory." We could add that the example should be run from the examples directory.

**Comment by ssolson** [comment]
Talking to Sean it seems that the issue here is that it was not clear that these need to be run as Jupyter Notebooks. I suggest at the "Examples" subheader we add a quick note on how to start a python notebook (or point to a Jupyter Notebook reference). And maybe on each example near the top say to run this as a Jupyter notebook (or point to a reference). It may seem obvious to us that these are notebooks by the extension but I don't think it is to someone coming in unfamiliar with Python/ notebooks and this would help clarify.

**Comment by kmruehl** [comment]
@ssolson sounds good to me. 

@SeanPluemer I suggest adding a note to the top of each example, and modifying the examples documentation here: https://mhkit-software.github.io/MHKiT/python.html#examples to specify these are Jupyter notebooks and how to run the.

**Comment by ssolson** [comment]
@SeanPluemer added a note clarifying that these were Jupyter notebooks in the documentation
