### ISSUE TITLE
Cannot access WPTO Hindcast Dataset since Friday 6/13/2023

### ISSUE THREAD

**Issue by radityadanu** [MHKiT-Software/MHKiT-Python#246]
### Describe the bug:
I had the script to access the WPTO hindcast dataset using the wave module as described in example and it worked before. However, the script is now spit error which I could not understand. I also tried to access the dataset using Marine Energy Atlas website (https://maps.nrel.gov/marine-energy-atlas/) and came up with no luck. 

### To Reproduce:
The same example from [examples/WPTO_hindcast_example.ipynb](https://github.com/MHKiT-Software/MHKiT-Python/blob/master/examples/WPTO_hindcast_example.ipynb). 

` data_type = '3-hour' # setting the data type to the 3-hour dataset
years = [1995]
lat_lon = (44.624076,-124.280097) 
parameter = 'significant_wave_height' 

Hs, metadata= wave.io.hindcast.hindcast.request_wpto_point_data(data_type,parameter,lat_lon,years) `

![image](https://github.com/MHKiT-Software/MHKiT-Python/assets/54357883/22f436c2-46ee-4074-a177-daad8713b910)

### Expected behavior:
It is expected to return a timeseries dataset for specific spatial boundaries. 

### Screenshots:
![image](https://github.com/MHKiT-Software/MHKiT-Python/assets/54357883/95547538-5eae-428b-a4d6-f4bb1e3762ce)

### Desktop (please complete the following information):
 - OS: Win 10 with Python 3.10
 - MHKiT Version: [0.5.1]

**Comment by ssolson** [comment]
Hey @radityadanu thank you for your interest in MHKiT.

This issue is most likely related to the API not returning data. This is not MHKiT but the server that hosts the data. I am working ot make the return as reliant as possible by cacheing data and making smaller requests. 

Just today you can find my latest comment discussing this issue for the wind data in #241.

I will look into your specific issue later this week and see if I have any luck.

@rpauly18 & @akeeste just wanted to put this on your radar that others continue to have issues accessing the data (not only from MHKiT but also from Atlas) pointing to a continuation of issues with the data hosting.

As I said I will follow up but just indicating your problem here is helpful for us to get resources and attention to address the data hosting issues.

**Comment by ssolson** [comment]
Raised the issue with the NREL development folks

https://github.com/NREL/developer.nrel.gov/issues/320

**Comment by radityadanu** [comment]
Hi @ssolson, thank you for your fantastic work! I tried your solution, and I can confirm that the problem is in the API. Sometimes I can access the data, but the error occurs randomly again. 

Thank you also for raising the issue to the correct desk! I think I could close this issue and follow up with [](https://github.com/NREL/developer.nrel.gov/issues/320)
