### ISSUE TITLE
Extraneous print()

### ISSUE THREAD

**Issue by mikebannis** [MHKiT-Software/MHKiT-Python#247]
The `print()` in [cdip.py](https://github.com/MHKiT-Software/MHKiT-Python/blob/e5916004ff0413f32f9559790582c95193acdd24/mhkit/wave/io/cdip.py#L455) appears to be extraneous. I'm running mhkit automatically every 10 minutes on AWS as part of a data processing pipeline and it's adding some clutter to the logs. This is a VERY minor issue, but that print does not appear intentional. I'm totally fine if it is intentional or the time isn't available to work on it. Thank you!

**Comment by ssolson** [comment]
@mikebannis thank you for your interest in MHKiT and bringing this up.  

I put the print statement there because processing the 2D variables takes a significant amount of time and we discuss this in the example notebook. It was essentially to indicate to the user that the reason the code is not progressing is due to the 2D variable processing.

There should ideally be a way to turn it off though as I can see now that in a production scenario this could be quite extraneous. I am open to any thoughts you may have on removing it and would be happy to help with a PR even if it is a simple as removing the print statement.

**Comment by mikebannis** [comment]
That makes sense. Possibly add a `silent=False` kwarg to `get_netcdf_variables()` and `request_parse_workflow()`? Based on the colon at the end of the print statement I expected some sort of progress indicator, like the current variable being processed, hence why I thought it may have been leftover code from debugging or similar. I'm a bit busy right now, but may have time to submit a PR later. Would you prefer me doing a fork or giving access to the repo? Zero rush. Thank you!

**Comment by mikebannis** [comment]
Just noticed you used Torrey Pines for the cdip example. I just learned that place existed the other day. Is there any particular reason you chose it?

**Comment by ssolson** [comment]
Hey Mike so that station was chosen because it was used as the example station by the CDIP to create their compendium examples:
https://cdip.ucsd.edu/themes/media/docs/documents/html_pages/compendium.html

It was added and discussed in PR #72.

**Comment by akeeste** [comment]
@mikebannis This issue is resolved by #273. Use the new ``silent`` argument to clean up the logs in your production environment.
