### ISSUE TITLE
CI: Wind hindcast API Calls

### ISSUE THREAD

**Issue by ssolson** [MHKiT-Software/MHKiT-Python#315]
The wind hindcast data currently takes greater than 3.5 hours to collect the needed data.

Can we get this down to 1 hr to be on par with the wave data?

![image](https://github.com/MHKiT-Software/MHKiT-Python/assets/13438942/ad282d9f-5ced-4357-a008-b0479b8b0efc)

**Comment by akeeste** [comment]
The metocean example pulls wind toolkit data and is pretty fast. We should look at replacing our test data with what's used in that example

**Comment by akeeste** [comment]
I'm attempting to look into this today. I started testing locally but it seems like I'm already being rate limited.

My initial testing indicates that multiparameter requests are running as expected (the metocean example only does this), but for some reason multiyear and multilocation requests are slowing down the tests.

**Comment by akeeste** [comment]
Hopefully #315 shows some performance improvements. But in the typical manner of pulling this data, it was successful once locally and then downloads started hanging for long times.

**Comment by akeeste** [comment]
This issue was largely addressed by #338 so I will close it for now. If the time required for the wind toolkit tests becomes problematic again, we should take the following discussed steps:
- Remove calling the wind toolkit API as a test
- store cached wind toolkit data on the repo
- test our functions solely using the stored data, not by calling the API.
- on master, call the API and test without the stored data
